### 城を取得する
GET http://localhost:8787/castle/get/1 HTTP/1.1

### 城を追加する
POST http://localhost:8787/castle/add HTTP/1.1
content-type: application/json

{
  "id": 1,
  "name": "名古屋城",
  "alias": ["蓮左城", "楊柳城", "柳ヶ城", "亀尾城", "鶴ヶ城", "金城"],
  "build_year": 1612,
  "coordinates": {
    "lat": 35.183333,
    "lng": 136.9
  },
  "place": {
    "pref": { "name": "愛知県", "id": 1 },
    "area": { "name": "尾張", "id": 2 },
    "city": { "name": "名古屋市", "id": 2 },
    "address": "中区本丸1-1"
  },
  "castle_tower": {
    "structure": {
      "layers": 7,
      "floors": 5
    }
  },
  "lords": [
    { "name": "尾張徳川家", "from": 1612, "to": 1616 },
    { "name": "尾張徳川家", "from": 1616, "to": 1700 }
  ],
  "type": "平城",
  "remains": ["石垣", "土塁", "堀"],
  "restorations": ["天守", "櫓"],
  "categories": ["特別史跡", "重要文化財"],
  "site": "https://www.nagoyajo.city.nagoya.jp/",
  "images": [
    "/images/sample.webp",
    "/images/sample2.webp",
    "/images/sample3.webp"
  ],
  "guides": [
    {
      "nearest_station": {
        "name": "名古屋城駅",
        "line": "名古屋市営地下鉄名城線",
        "distance": 0.2
      }
    }
  ]
}

### カテゴリを取得する
GET http://localhost:8787/castle/categories/get HTTP/1.1

### カテゴリを追加する
POST http://localhost:8787/castle/categories/add HTTP/1.1
content-type: application/json

{
    "categories": [
        "日本100名城",
        "続日本100名城",
        "日本三大名城",
        "日本三大水城",
        "日本三大山城",
        "日本三大湖城",
        "日本三大海城",
        "現存12天守",
        "世界遺産",
        "国宝5城"
    ]
}

### 形態を取得する
GET http://localhost:8787/castle/types/get HTTP/1.1

### 形態を追加する
POST http://localhost:8787/castle/types/add HTTP/1.1
content-type: application/json

{
    "types": [
        "平城",
        "平山城",
        "山城",
        "海城",
        "湖城"
    ]
}
