### 城マーカーを取得する
GET {{host}}/markers?latMin=33.1803328170113&latMax=37.1803328170113&lngMin=134.9082307815552&lngMax=138.9082307815552&scale=1 HTTP/1.1

### 城マーカーを取得する(全て)
GET {{host}}/markers?latMin=0&latMax=9999&lngMin=0&lngMax=9999 HTTP/1.1

### 城マーカーを取得する(エラー)
GET {{host}}/markers?lngMin=134.9082307815552&lngMax=138.9082307815552&scale=1 HTTP/1.1

### 城マーカーを追加する
POST {{host}}/markers HTTP/1.1
Content-Type: application/json

{
    "markers": [
        {
            "name": "サンプル城",
            "coordinates": {
                "lat": 999,
                "lng": 888
            },
            "scale": 1
        }
    ]
}

### 城マーカーを削除する
DELETE {{host}}/markers HTTP/1.1
Content-Type: application/json

{
    "ids": [
        "サンプル城_999_888"
    ]
}

### マーカー情報を取得する
GET {{host}}/markers/data HTTP/1.1